DROP SEQUENCE SEQ_MAILBOX;
DROP TABLE TBL_MAILBOX;

CREATE SEQUENCE SEQ_MAILBOX;
CREATE TABLE TBL_MAILBOX(
	BNO NUMBER(10, 0),
	WRITER VARCHAR2(50),
	RECIPIENT VARCHAR2(50),
	TITLE VARCHAR2(200),
	CONTENT VARCHAR2(2000),
	REGDATE DATE DEFAULT SYSDATE
);

ALTER TABLE TBL_MAILBOX ADD CONSTRAINT PK_MAILBOX PRIMARY KEY (BNO);
ALTER TABLE TBL_MAILBOX ADD CONSTRAINT FK_MAILBOX_MEMBERS FOREIGN KEY (BNO) REFERENCES MEMBERS(MEMBERS_SEQ);
ALTER TABLE TBL_MAILBOX DROP CONSTRAINT UQ_MAILBOX;

INSERT INTO TBL_MAILBOX VALUES(
	SEQ_MAILBOX.NEXTVAL, 'mandoo180@gmail.com', '수신인', '테스트 제목', '테스트 내용 하나둘세넷다섯여섯일곱여덟ㅇ이이이', SYSDATE
);

SELECT * FROM TBL_MAILBOX;
DELETE FROM TBL_MAILBOX WHERE BNO > 1;


SELECT * FROM
(
SELECT /*+INDEX_DESC(TBL_MAILBOX PK_MAILBOX)*/
ROWNUM RN, BNO, WRITER, RECIPIENT, TITLE, CONTENT, REGDATE
FROM TBL_MAILBOX
WHERE (RECIPIENT LIKE '%'||'수신인'||'%')
AND ROWNUM <= 200 AND WRITER = 'sender'
)
WHERE RN > 0;


SELECT COUNT(*) FROM TBL_MAILBOX WHERE BNO > 0 AND WRITER = 'sender';


---------------------------------


DROP SEQUENCE SEQ_REPLY;
DROP TABLE TBL_REPLY;
CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	RNO NUMBER (10, 0) PRIMARY KEY,
	BNO NUMBER (10, 0) NOT NULL,
	REPLY VARCHAR2(1000) NOT NULL,
	REPLYER VARCHAR2(50) NOT NULL,
	REPLYDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);



ALTER TABLE TBL_REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (RNO);

ALTER TABLE TBL_REPLY ADD CONSTRAINT FK_REPLY_MAILBOX FOREIGN KEY (BNO) REFERENCES TBL_MAILBOX (BNO);
ALTER TABLE TBL_REPLY DROP CONSTRAINT FK_REPLY_MAILBOX;

INSERT INTO TBL_REPLY (RNO, BNO, REPLY, REPLYER)VALUES(
	SEQ_REPLY.NEXTVAL, 69, '댓글', '악플러'
);

SELECT * FROM TBL_REPLY;

--------------------------------------------

DROP TABLE TBL_ATTACH;

CREATE TABLE TBL_ATTACH(
	UUID VARCHAR2(100) NOT NULL,
	UPLOADPATH VARCHAR2(200) NOT NULL,
	FILENAME VARCHAR2(100) NOT NULL,
	FILETYPE CHAR(1) DEFAULT 'I',
	BNO NUMBER(10, 0)
);

SELECT * FROM TBL_ATTACH;

ALTER TABLE TBL_ATTACH ADD CONSTRAINT PK_ATTACH PRIMARY KEY (UUID);

ALTER TABLE TBL_ATTACH ADD CONSTRAINT PK_MAILBOX_ATTACH FOREIGN KEY (BNO)
REFERENCES TBL_MAILBOX(BNO);
