---MEMBERS

--회원가입 및 로그인
CREATE SEQUENCE members_SEQ
START WITH 1
INCREMENT BY 1;
--회원
DROP TABLE MEMEBERS;
CREATE TABLE members
(
    members_seq        INT             NOT NULL, 
    members_name       VARCHAR2(20)    NOT NULL, 
    members_email      VARCHAR2(20)    NOT NULL,
    members_pw         VARCHAR2(20)    NOT NULL,
    members_EmailChecked    VARCHAR2(5),
    CONSTRAINT MEMBERS_PK PRIMARY KEY (members_seq)
);

ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK PRIMARY KEY (MEMBERS_SEQ);
ALTER TABLE MEMBERS DROP CONSTRAINT MEMBERS_PK;
ALTER TABLE MEMBERS ADD UNIQUE (MEMBERS_EMAIL);

INSERT INTO MEMBERS VALUES(
	MEMBERS_SEQ.NEXTVAL, 'choi', 'highkick89@naver.com', '1234', 'true');

SELECT * FROM MEMBERS;
SELECT * FROM MEMBERS WHERE MEMBERS_EMAIL = 'mandoo180@gmail.com';


---TBL_MAILBOX
DROP SEQUENCE SEQ_MAILBOX;
DROP TABLE TBL_MAILBOX;

CREATE SEQUENCE SEQ_MAILBOX;
CREATE TABLE TBL_MAILBOX(
	BNO NUMBER,
	TEMPLATE VARCHAR2(100),
	EMAIL VARCHAR2(255),
	TITLE VARCHAR2(255),
	CONTENT VARCHAR2(2500),
	REGDATE DATE DEFAULT SYSDATE
);

INSERT INTO TBL_MAILBOX (BNO, TEMPLATE, EMAIL, TITLE, CONTENT) VALUES(
	SEQ_MAILBOX.NEXTVAL, 'template1', 'highkick89@naver.com','TITLE', 'CONTENT'
);

SELECT * FROM TBL_MAILBOX;
DELETE FROM TBL_MAILBOX WHERE BNO > 0;

ALTER TABLE TBL_MAILBOX ADD TEMPLATE NUMBER;
ALTER TABLE TBL_MAILBOX DROP COLUMN TEMPLATE;
ALTER TABLE TBL_MAILBOX ADD REGDATE DATE DEFAULT SYSDATE;

ALTER TABLE TBL_MAILBOX DROP CONSTRAINT PK_MAILBOX;
ALTER TABLE TBL_MAILBOX DROP CONSTRAINT FK_MAILBOX_MEMBER;

ALTER TABLE TBL_MAILBOX ADD CONSTRAINT PK_MAILBOX PRIMARY KEY (BNO);
ALTER TABLE TBL_MAILBOX ADD CONSTRAINT FK_MAILBOX_MEMBER FOREIGN KEY (MNO) REFERENCES MEMBERS (MEMBERS_SEQ);

SELECT TBL_MAILBOX.WRITER, MEMBERS.MEMBERS_EMAIL
FROM TBL_MAILBOX
INNER JOIN MEMBERS ON TBL_MAILBOX.WRITER = MEMBERS.MEMBERS_EMAIL;

SELECT * FROM TBL_MAILBOX WHERE MNO = 5 ORDER BY BNO DESC;
DELETE FROM TBL_MAILBOX WHERE MNO =5;
SELECT TBL_MAILBOX.BNO, TBL_MAILBOX.WRITER, TBL_MAILBOX.TEXT1
FROM TBL_MAILBOX
LEFT JOIN TBL_MAILBOX ON MEMBERS.MEMBERS_EMAIL = TBL_MAILBOX.WRITER;

-------- TBL_ATTACH


DROP TABLE TBL_ATTACH;

CREATE TABLE TBL_ATTACH(
	UUID VARCHAR2(100) NOT NULL,
	UPLOADPATH VARCHAR2(200) NOT NULL,
	FILENAME VARCHAR2(100) NOT NULL,
	FILETYPE CHAR(1) DEFAULT 'I',
	BNO NUMBER(10, 0)
);

SELECT * FROM TBL_ATTACH;

ALTER TABLE TBL_ATTACH DROP CONSTRAINT PK_ATTACH;
ALTER TABLE TBL_ATTACH DROP CONSTRAINT PK_MAILBOX_ATTACH;

ALTER TABLE TBL_ATTACH ADD CONSTRAINT PK_ATTACH PRIMARY KEY (UUID);
ALTER TABLE TBL_ATTACH ADD CONSTRAINT PK_MAILBOX_ATTACH FOREIGN KEY (BNO)
REFERENCES TBL_MAILBOX(BNO);


SELECT BNO, TEMPLATE, TITLE, CONTENT, REGDATE   FROM 
(   SELECT /*+INDEX_DESC(TBL_MAILBOX IDX_MAILBOX)*/
ROWNUM RN, BNO, TEMPLATE, TITLE, CONTENT, REGDATE  
FROM    TBL_MAILBOX   WHERE EMAIL = 'highkick89@naver.com'   AND BNO > 0   AND ROWNUM <= 10 )   
WHERE RN > 0
