--그룹
CREATE SEQUENCE GROUP_ADDRESS_SEQ;

CREATE TABLE GROUP_ADDRESS_TABLE(
   group_seq NUMBER PRIMARY KEY,
   group_title   VARCHAR2(30),
   group_date DATE DEFAULT SYSDATE,
   members_seq NUMBER NOT NULL,
    cnt NUMBER NOT NULL,
   CONSTRAINT GROUP_MEMBER_SEQ  FOREIGN KEY(MEMBERS_SEQ) REFERENCES members(MEMBERS_SEQ)
);

--주소록
CREATE SEQUENCE address_customer_seq INCREMENT BY 1 START WITH 1;

CREATE TABLE ADDRESS_TABLE(
   customer_seq NUMBER PRIMARY KEY,
   customer_name VARCHAR2(30),
   customer_email VARCHAR2(30),
   group_seq NUMBER NOT NULL,
    members_seq NUMBER NOT NULL,
   CONSTRAINT admin_group_seq  FOREIGN KEY(group_seq) REFERENCES GROUP_ADDRESS_TABLE(group_seq),
   CONSTRAINT ADDRESS_FK_MEMBER_ID  FOREIGN KEY(MEMBERS_SEQ) REFERENCES MEMBERS(MEMBERS_SEQ) 
);

commit;